### ISSUE TITLE
unable to connect to remote frida-server: closed

### ISSUE THREAD

**Issue by kevin-valerio** [m0bilesecurity/RMS-Runtime-Mobile-Security#1]
Hello,

Here is the message I've got when I try to use RMS : "[process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
frida.**ServerNotRunningError: unable to connect to remote frida-server: closed**"

The FRIDA server seems to be closed. Any idea why ?

**Comment by m0bilesecurity** [comment]
Hey,
Is the FRIDA server up and running on the target device?

Refer to the official FRIDA guide for the installation: https://frida.re/docs/android/
