### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by Azult** [m0bilesecurity/RMS-Runtime-Mobile-Security#10]
Hi guys!

First of all this is a great tool you got!

I just wanted to ask you to modify the class filter from 'startsWith' to 'search'.
This is actually implements Regex and thus makes the filtering a lot more efficient.

This is the modification I made to `loadclasseswithfilter`:
```
loadclasseswithfilter: function (filter) {
    var loaded_classes = []
    Java.perform(function () {
      Java.enumerateLoadedClasses({
        onMatch: function (className) {

          //check if a filter exists
          if (filter != null) {
            if (className.search(filter.trim()) > -1 ) {
              loaded_classes.push(className)
            }
          }
        },
        onComplete: function () {
          loaded_classes.sort()
        }
      });
    })
    return loaded_classes;
  }
```

Hope you guys agree with me.

Thanks!

**Comment by m0bilesecurity** [comment]
Hey @Azult many thanks for the suggestion.
Please open a **Pull Request** instead of an issue. 
I'll be happy to test and merge your code.
Thanks
