### ISSUE TITLE
Not working with Frida 16.0.2

### ISSUE THREAD

**Issue by CodingBeaner** [m0bilesecurity/RMS-Runtime-Mobile-Security#103]
Console:```[Error: Unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use]```
Both Desktop and Smartphone are using Frida 16.0.2
Frida-ps -U also works from console
Only 1 device is connected to my PC

**Desktop:** 
 - OS: Windows 10
 - Browser: Brave Browser

**Smartphone:**
 - Device: iPhone 7
 - OS: 14.2
 - Frida Server version: 16.0.2

**Comment by poldenais** [comment]
Hi @CodingBeaner I am getting the exact same issue. I thought I was using the wrong Frida version so reinstalled it and also restarted RMS but get the same error. 

Thanks

**Comment by brunoaduarte** [comment]
Seems the project is dead. Last update was more than 1 year ago.

**Comment by m0bilesecurity** [comment]
Hey, I'll try to do my best but I don't have much free time at the moment. 
What about updating directly the frida library to the latest version?

**Comment by Awais-Akram** [comment]
@CodingBeaner @poldenais 
For now the possible solution is downgrade frida tool and frida sever.
Kill rms and frida before doing this
`pip uninstall frida-tools`
`pip install -Iv frida-tools=11.0.0` (Frida will be downgrade to 15.2.2)
`npm install -g rms-runtime-mobile-security` (Run this even if rms already installed)
Also downgraded your Frida Sever which you installed on your mobile device or in any emulator to 15.2.2
Establish connection with frida sever (steps already mentioned on [Frida](frida.re/docs/android)  site)
`rms`

**Comment by m0bilesecurity** [comment]
Fixed - RMS 📱🔥 version 1.5.12 is out with support for frida 16 [02c2381](https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/commit/02c2381ef6a56c4cbb3da47e22821289cfc56b06)
