### ISSUE TITLE
String Comparison API hook

### ISSUE THREAD

**Issue by brunoaduarte** [m0bilesecurity/RMS-Runtime-Mobile-Security#104]
Shouldn't the args be printed in the args fields instead of only their types?

```
[API_Monitor]
{
  "category": "String Comparison",
  "class": "java.lang.String",
  "method": "equals",
  "args": "[\"<instance: java.lang.Object, $className: java.lang.String>\"]",
  "returnValue": "true",
  "calledFrom": "\u0007"
}
```

**Comment by m0bilesecurity** [comment]
Ciao @brunoaduarte, you need to analyse every object one by one.
Do you have some time to improve the API_Monitor script? 
https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/blob/64faab0cf8112ebab00c9ef83782e8b9a586a8d7/agent/RMS_core.js#L487
Thanks
