### ISSUE TITLE
 SpringBoard is NOT available on your device!

### ISSUE THREAD

**Issue by poldenais** [m0bilesecurity/RMS-Runtime-Mobile-Security#106]
**Describe the bug** [Required]

Im getting the Springboard error below when trying to connect to an app in RMS:
Mobile OS: iOS
Target Package: com.l%%%%%%%.£££££ (hid the package name)
System Package: SpringBoard

SpringBoard is NOT available on your device!

**To Reproduce** [Required]
Attempt to connect to the application using RMS

**Expected behavior** [Optional]
Can't connect

**Desktop (please complete the following information):** [Required]
 - MacBook Pro 

**Smartphone (please complete the following information):** [Required]
 - Device: Apple iPad mini 2
 - OS: 12.5.5
 - Frida Server version: 16.0.2

**Comment by m0bilesecurity** [comment]
Duplicate #72 
I only tested RMS with iOS 13. I don't have an iOS 12 device to understand what is the issue with iOS 12.
