### ISSUE TITLE
Excpetion: Error: Unable to connect to remote frida-server: closed

### ISSUE THREAD

**Issue by zulfakar404** [m0bilesecurity/RMS-Runtime-Mobile-Security#108]
Package Name: 
Mode: Attach
Frida Startup Script: None
APIs Monitors:
Clicks - MotionEvent
Exception: Error: Unable to connect to remote frida-server: closed
com.android.systemui is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
Excpetion: Error: Unable to connect to remote frida-server: closed

**Comment by m0bilesecurity** [comment]
Please provide more info.
