### ISSUE TITLE
Crash when Starting RMS on Rootless

### ISSUE THREAD

**Issue by Lunascaped** [m0bilesecurity/RMS-Runtime-Mobile-Security#114]
**Describe the bug** [Required]
Whenever RMS tries to inject into anything, it crashes the process with "EXEC_BAD_ACCESS", this also causes my Springboard to crash as it tries to hook into it and crashes it.

**To Reproduce** [Required]
1. Fill in the starting confg and hit "Start RMS"
2. Processes crash on device, if springboard is being used it causes a respring into safe mode.

**Desktop (please complete the following information):** [Required]
 - OS: Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):** [Required]
 - Device: iPhone 12 Pro Max (Jailbroken with Dopamine, latest version)
 - OS: 15.4.1
 - Frida Server version: 16.1.0 (Uses miticollo's modified version as thats the only working rootless Frida server atm)
 - Package Name: Any
 - Class name: [e.g. sg.vantagepoint.a.c] (optional)
 - Method name: [e.g. public static boolean c()] (optional)

**Console Logs** [Required]
NEW CONFIG
{
  device_type: 'USB',
  system_package_Android: 'com.android.systemui',
  system_package_iOS: 'Springboard',
  device_args: { host: '', id: '' }
}

Package Name: <redacted, happens on all packages anyway>
Mode: Attach
Frida Startup Script: None
APIs Monitors: None
Exception: Error: Script is destroyed
Springboard is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!

**Additional context** [Optional]
Springboard crash log: https://pastebin.com/vwfz5fTG

**Comment by m0bilesecurity** [comment]
Frida 16.1.4 is out with the following changelog:

iOS: Add support for rootless systems

RMS v1.5.19 (just released 🎉) includes support for the new Frida release 😀

Maybe you can test it and let me know if now RMS is working with Dopamine ? 

Thx
