### ISSUE TITLE
i need to help , i can't use 

### ISSUE THREAD

**Issue by wonglam1604** [m0bilesecurity/RMS-Runtime-Mobile-Security#118]
when i spawn show error of left

com.android.systemui is NOT available on your device!

For a better RE experience, Click [here](http://127.0.0.1:5000/config) to change it!
FRIDA crashed

Error description:
Error: Need Gadget to attach on jailed Android; its default location is: C:\Users\{USER}\AppData\Local\Microsoft\Windows\INetCache\frida\gadget-android-arm64.so

**Comment by m0bilesecurity** [comment]
Is your test device rooted?
