### ISSUE TITLE
Feature request: Word Warp for output console

### ISSUE THREAD

**Issue by phieulang1993** [m0bilesecurity/RMS-Runtime-Mobile-Security#121]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the output console has some lines that are too long, so I always have to scroll to continuously check

**Describe the solution you'd like**
I suggest adding a button for enabling Word Warp for the 3 output consoles on the consoles tab

**Comment by m0bilesecurity** [comment]
Hey @phieulang1993 
do you have time to work on this feature?
Thx
