### ISSUE TITLE
Support for latest version of Node 20.9.0 LTS

### ISSUE THREAD

**Issue by drain** [m0bilesecurity/RMS-Runtime-Mobile-Security#122]
Hi,

Experiencing the same issue as mentioned on https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/issues/98
Downgrading to v18.12.1 works, but it would be nice to have the latest version supported.

**Comment by m0bilesecurity** [comment]
Fixed in the new version of RMS 1.5.20
https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/releases/tag/1.5.20
Thanks 🙏🏻
