### ISSUE TITLE
RMS not working

### ISSUE THREAD

**Issue by shubhamsonani** [m0bilesecurity/RMS-Runtime-Mobile-Security#123]
I installed latest version of RMS and frida 16.0+. I am using android studio's version 7 emulator with architecture x86_64. Now the error I am getting is this Package Name: owasp.mstg.uncrackable1
Mode: Spawn
Frida Startup Script: None
APIs Monitors: None
Exception: Error: Process not found
com.android.systemui is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
Excpetion: Error: Command failed: 99

![Screenshot 2023-11-02 220328](https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/assets/80889696/77116e8a-4edb-4c18-80eb-c1b05170eb43)

**Comment by shubhamsonani** [comment]
This issue is solved, I had manually rooted android studio's emulator. It worked then. My observation is - if you use rooted emulator of Android Studio, RMS will show "Command failed", as it is not able to grab the package "com.system.ui" which is system level package. Now, if the emulator is rooted (Android Studio), I think we have to give some permission first in "ADB shell" to access those packages by RMS. For Now, workaround is, to get android 10+ in Studio's emulator (Google play one), root it with "ROOTAVD" tool (as this tool works on 10+ versions.). Download frida-server and gadget with your emulator's architecture. Place the Frida-gadget (rename it to gadget-android-arm64.so) in "C:\users\username\local\microsoft\windows\INetCache\frida\..) and start the frida server in android. Now RMS should connect with your desired application.

**Comment by m0bilesecurity** [comment]
Thx 👏🏻
