### ISSUE TITLE
RMS added to JAMBOREE!

### ISSUE THREAD

**Issue by freeload101** [m0bilesecurity/RMS-Runtime-Mobile-Security#125]
Just wanted to say thank you for this tool not sure what the kids are using now days but hope this will help with next steps on project! Let me know if you have any time or know any classes I can learn more on bypassing and encrypted payloads especially.

Java Android Magisk Burp Objection Root Emulator Easy (JAMBOREE)  
https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy

**Comment by m0bilesecurity** [comment]
Ciao @freeload101, great news thanks! 
Is there something I need to do to maintain the compatibility? 
Thx Paolo
