### ISSUE TITLE
Install error with npm installation

### ISSUE THREAD

**Issue by Jane151013** [m0bilesecurity/RMS-Runtime-Mobile-Security#129]
Hi all,
    I've tried to install RMS with npm install,include development mode.But both have the same error as below:
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'D:\\Program Files\\RMS-Runtime-Mobile-Security\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\Program Files\RMS-Runtime-Mobile-Security\node_modules\rxjs\dist\esm5\internal'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'D:\\Program Files\\RMS-Runtime-Mobile-Security\\node_modules\\rxjs\\dist\\esm5\\internal'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path D:\Program Files\RMS-Runtime-Mobile-Security\node_modules\frida
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install aborted
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.10.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.9 found at "D:\Program Files\Python\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.34031.81) found at:
npm ERR! gyp info find VS "D:\Program Files\Microsoft Visual Studio2019\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn D:\Program Files\Python\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'D:\\Program Files\\RMS-Runtime-Mobile-Security\\node_modules\\frida\\build\\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\20.10.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\20.10.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.10.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=D:\\Program Files\\RMS-Runtime-Mobile-Security\\node_modules\\frida',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'D:\\Program Files\\RMS-Runtime-Mobile-Security\\node_modules\\frida\\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: D:\Program Files\RMS-Runtime-Mobile-Security\node_modules\frida) while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\npm\node_modules\node-gyp\lib\configure.js:271:18)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.17763
npm ERR! gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Program Files\RMS-Runtime-Mobile-Security\node_modules\frida
npm ERR! gyp ERR! node -v v20.10.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok

The environment info:
OS:windows 10
frida:16.1.10
npm:10.2.5

**I have also tried the suggestions on https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/issues/50 and https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/issues/51,but none of them is usefull.**

other solutions on googles have tried(not usefull):
reinstall frida
npm install --unsafe-perm

Hope someone can give some suggestion to solve this problem,TKS

**Comment by Jane151013** [comment]
![Uploading screenshot-20240108-164113.png…]()

**Comment by mr-bipolar** [comment]
check node version.

node 16.x -  work  [ checked ]
node 18.x - not work [ checked ]
node 20.x - work [ checked ]

install node 18 or 20

curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install -g rms-runtime-mobile-security
pip3 install frida-tools

=======================
My setup 
os : linux
node : v20.4.1
npm : 10.7.0
frida : 16.3.3
