### ISSUE TITLE
Feature Request : Automatically switch to Console tab after submitting Custom Frida script

### ISSUE THREAD

**Issue by Chan9390** [m0bilesecurity/RMS-Runtime-Mobile-Security#2]
The [current GIF in readme](https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security#6-inject-your-favorite-frida-custom-scripts-on-the-fly) shows the custom frida output in the terminal where the flask server's output is also present.

On checking out the feature, I found that the output of custom script is also showed in the "Console Output" tab.

It would be great it the "Console Output" tab is showed after submitting the custom payload.

**Comment by m0bilesecurity** [comment]
Done 😉
