### ISSUE TITLE
Not Connecting Devices

### ISSUE THREAD

**Issue by z3dc0ps** [m0bilesecurity/RMS-Runtime-Mobile-Security#21]
![Capture](https://user-images.githubusercontent.com/61974788/84994395-3e68eb80-b168-11ea-8b8e-d693970a1e30.JPG)

**Comment by m0bilesecurity** [comment]
As reported by the error message, is FRIDA server up and running on the target device?

Refer to the official FRIDA guide for the installation: https://frida.re/docs/android/

**Comment by z3dc0ps** [comment]
yes , it's connecting now, Please provide some tutorials too.

thanks
