### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by z3dc0ps** [m0bilesecurity/RMS-Runtime-Mobile-Security#22]
![1](https://user-images.githubusercontent.com/61974788/85018210-69fccd80-b18a-11ea-8db7-b91d93ab59d1.JPG)
![2](https://user-images.githubusercontent.com/61974788/85018240-78e38000-b18a-11ea-9955-edfd12a36417.JPG)

**Comment by z3dc0ps** [comment]
Application Used:
      diva-beta - http://www.payatu.com/wp-content/uploads/2016/01/diva-beta.tar.gz

**Comment by m0bilesecurity** [comment]
@z3dc0ps if you are trying to **attach** a process, make sure that the app is running. 
Try to spawn the app instead.
