### ISSUE TITLE
frida.ProcessNotFoundError: unable to find process with name 'bundleID'

### ISSUE THREAD

**Issue by Daemonceltics** [m0bilesecurity/RMS-Runtime-Mobile-Security#29]
Env:
frida 12.11.7 
iOS 12

WebServer get bundleID not process name, then ... 
![image](https://user-images.githubusercontent.com/14012342/89369245-20ebe300-d710-11ea-8c51-7eb913410332.png)

**Comment by m0bilesecurity** [comment]
Hey @Daemonceltics, thanks for using RMS.
if you are attaching an app (instead of spawning), please make sure that it is up and running.
Please let me know if the issue still persists.
Best

**Comment by m0bilesecurity** [comment]
Attaching a process on iOS requires its **Name** instead of the **identifier**.
Issue fixed in commit 3b8a9db 🚀
Git pull and you're fine 😉
Many thanks @Daemonceltics
