### ISSUE TITLE
FIX WARNING in __init__: WebSocket transport not available.

### ISSUE THREAD

**Issue by punishell** [m0bilesecurity/RMS-Runtime-Mobile-Security#30]
Install gevent-websocket, does not fix the problem, you could add to requirements also: eventlet.
Cheerz

**Comment by m0bilesecurity** [comment]
hey @punishell 
The issue is related to this PR #16 
More details about what I tried in issue number #23 

Please let me know what you have done in order to get eventlet working on RMS 😉

Best
