### ISSUE TITLE
SpringBoard is NOT available on your device | incompatible Mach-O image

### ISSUE THREAD

**Issue by sushi2k** [m0bilesecurity/RMS-Runtime-Mobile-Security#31]
**Describe the bug** [Required]
Installed RMS and can access via localhost:5000. iOS device is detected, but when trying to attach or spawn an app I am getting the following error.

**To Reproduce** [Required]
1. Open RMS, select iOS and any package name, spawn|attach and Start RMS.
2. See error

```
Package Name: com.apple.podcasts
Mode: Spawn
Device: Device(id="00008020-000118563411802E", name="iPad 4", type='usb')
BETA: False
Frida Startup Script: None
APIs Monitors: None


incompatible Mach-O image
SpringBoard is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
[2020-08-23 13:48:25,614] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "mobilesecurity.py", line 424, in device_management
    pid = device.spawn([target_package])
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Users/sven/opt/anaconda3/lib/python3.7/site-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: incompatible Mach-O image
```

**Desktop (please complete the following information):** [Required]
 - OS: macOS 10.15.5
 - Browser Chrome (latest)

**Smartphone (please complete the following information):** [Required]
 - Device: [e.g. Genymotion, AVD, Google Pixel 3]
 - Frida Server version: [e.g. 12.8.20]
 - Package Name: [e.g. com.example.app]
 - Class name: [e.g. sg.vantagepoint.a.c] (optional)
 - Method name: [e.g. public static boolean c()] (optional)

 I tried with a jailbroken iPad 4 (iOS 13.5) and an iPhone 6S (12.4). Both have latest version of Frida installed via Cydia (12.11.10) and are jailbroken with unc0ver. 

**Console Logs** [Required]
See above

![image](https://user-images.githubusercontent.com/5951320/90972028-3fdbd900-e548-11ea-820c-80256b9eb0d5.png)

![image](https://user-images.githubusercontent.com/5951320/90972017-263a9180-e548-11ea-9f20-48b72af4ac27.png)

![image](https://user-images.githubusercontent.com/5951320/90972019-2cc90900-e548-11ea-987a-defdb03ec75b.png)

**Comment by m0bilesecurity** [comment]
Hey @sushi2k 
Great 🎉 please let me know what you think about RMS if you have the chance to play with it for a while 😉

P.S. from your last screenshot it seems that you still have an issue with the Springboard... That is really strange.

Before spawning/attaching the target app, RMS always tries to attach the Springboard in order to get the list of all the classes that are already loaded in memory before the launch of the target app.

**Comment by sushi2k** [comment]
> P.S. from your last screenshot it seems that you still have an issue with the Springboard... That is really strange.
> 
> Before spawning/attaching the target app, RMS always tries to attach the Springboard in order to get the list of all the classes that are already loaded in memory before the launch of the target app.

I saw that. For now it works :-) I try to have a look at this week. Thanks
