### ISSUE TITLE
Option to clear console output

### ISSUE THREAD

**Issue by GrepItAll** [m0bilesecurity/RMS-Runtime-Mobile-Security#32]
**Is your feature request related to a problem? Please describe.**
No ability to clear output console

**Describe the solution you'd like**
A button to clear the 3 output consoles on the consoles tab

**Describe alternatives you've considered**
Current workaround is to disconnect and reconnect RMS to the device

**Comment by m0bilesecurity** [comment]
Implemented in commit 4e6e9cf51aa381dd2b5422ac9b067e643afb31ec
Git pull and and test the new reset button 😉
Best

**Comment by GrepItAll** [comment]
Great stuff, thanks @m0bilesecurity!
