### ISSUE TITLE
PixelXL lineageos 17.1 (android10) is not supported.

### ISSUE THREAD

**Issue by daeinlee** [m0bilesecurity/RMS-Runtime-Mobile-Security#34]
Thank you for making a great tool called rms.
This tool is really cool.

I sent an e-mail because I had a question about RMS.
This email has been translated with Google Translate and there may be some misinterpretation.
I tried testing with lineage os (android 10) and it couldn't connect to the device.
The PC emulator has already confirmed that it is connected. (Nox App player android5)
So, can you know exactly what device it supports?

And, I have a suggestion.

I am working on security verification related to games.
Is it possible to support a script that hooks libil2cpp.so of unity game to rms?

I know it won't be easy.
It has already been implemented in linEngine, which is serviced in Korea, but there are few devices supported.

LinEngine URL: http://linforum.kr/bbs/board.php?bo_table=linEngines

Have a good weekend.
If you give me an answer, I think it will be very helpful.

**Comment by m0bilesecurity** [comment]
Ciao @daeinlee 
is FRIDA server up and running on the target device?

Refer to the official FRIDA guide for the installation: https://frida.re/docs/android/
OR
below you can find some cool projects that can help you to auto install, update and run frida on your Android device:

* [MagiskFrida - Android](https://github.com/ViRb3/magisk-frida)
* [FridaLoader - Android](https://github.com/dineshshetty/FridaLoader)

**P.S.** Device must be **rooted**.

**Comment by daeinlee** [comment]
Thanks for answering the question.

When I tested, the Frida server was already loading, and I checked that Frida was well connected

Let's test it with another device.

**Comment by daeinlee** [comment]
I solved it by connecting to Android 8.0
