### ISSUE TITLE
Dex Classes

### ISSUE THREAD

**Issue by relaxedricky** [m0bilesecurity/RMS-Runtime-Mobile-Security#36]
**Is your feature request related to a problem? Please describe.**
I had planned to use this project to help with an assessment, however, the "load classes" failed to load the apps classes, after looking into the app it's due to the classes being "dex classes"

**Describe the solution you'd like**
Have the "load classes"  button load classes AND dex classes

**Describe alternatives you've considered**
In this instance, I went to ncc's house along with custom Frida scripts

**Comment by m0bilesecurity** [comment]
Ciao @relaxedricky 
can you better describe the issue providing some screenshots and the APK file?
Many thanks

**Comment by relaxedricky** [comment]
Hi,

If you take a look at the following:

https://github.com/nccgroup/house/blob/efbe792d045cdfb9521bc852a06a7d43195e3c64/scripts/enum/enum_skl.js

If you look at enumDexClasses it should give you some more idea as well as the following:

https://www.boldare.com/blog/differences-between-class-and-dex-files-in-java-android/

I can't provide the apk as it's for client work

**Comment by m0bilesecurity** [comment]
Hey @relaxedricky 
many thanks for all the info provided.
With the new commit 40c3ab825777cb01bb3de2e624a0bcfd357cb98e it is now possibile to enumerate Dex Classes via a **FRIDA custom script**. 

**Source Code here**: https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/blob/master/custom_scripts/Android/dex_classes_enumeration.js

Not sure if it is possible to integrate it directly inside the main RMS agent (**loadclasses** and **loadclasseswithfilter**) and start hooking methods on the fly.

If you have time you can try 🙏🏻
Let me know!
Best
