### ISSUE TITLE
Android device detection error

### ISSUE THREAD

**Issue by vikramn99** [m0bilesecurity/RMS-Runtime-Mobile-Security#37]
Android device detection doe's not happence properly.

Devices using:
Computer System OS: Windows 10 Home 
Android device: Realme X2 [Android 10]

Frida server is properly running in targeted device. 

Issue
Frida server is properly running  in targeted android device (By self verified), and also device is  connected computer with usb connection.
The requirements are satisfied. but still the runtime mobile security RMS is failing to get the device port(or device detection ).

I am using another dynamic analysis tool called house 
Link: https://github.com/nccgroup/house. it works well and good.
Please look out this tool source code for more details.

Note: Both Screenshots are taken at same time, both tools are running same time with different port [ RMS:Port=5000, House:Port=9000 ]

RMS Web API Screenshot: https://codex-scripts.xyz/RMS_web_api.png
House Web API Screenshot: https://codex-scripts.xyz/House_web_api.png

Some times device connects properly, but the connecting chances are very less. I need to reboot the computer and mobile upto 4 to 6 times to get connected with RMS.

I am done some steps to avoid the issue. but still issue not resolved
1) Rebooting computer and also mobile
2) Restarting RMS
3) Restarting frida server in android 

i am very happy with this tool. but the only thing is connection problem.

Please look out this issue

**Comment by m0bilesecurity** [comment]
Hey @vikramn99 vikramn99,
I'm not able to reproduce the issue and it's also the first time that I hear about that.

Do you have multiple devices connected? RMS is currently not able to manage multiple devices so please do not connect more than one device at the same time.

Can you try with another device or with Genymotion/AVD?

Best

**Comment by vikramn99** [comment]
Connection issue solved

Runtime logs on time not showing.
I need to reload the page to get the logs.

**Comment by m0bilesecurity** [comment]
Great, what was the problem?

Regarding the logs not showed in the web interface, please make sure to use Google Chrome (current Socket implementation is not working on other browsers)

Let me know 😉

**Comment by vikramn99** [comment]
I am using only chrome browser.
All are fine.
But on time logs not showing.
I need to reload the page to het logs in web API.

**Comment by m0bilesecurity** [comment]
What do you exactly mean with "on time logs"? Can you provide a screenshot?

Thanks

**Comment by vikramn99** [comment]
Yes

**Comment by vikramn99** [comment]
Shall we expect bytes to string ?
I mean the args output is in bytes mode.
Instead of bytes i need it in string format.
Is any settings are their to get it ?

Because i need to covert bytes to string every time.

This tool was amazing.
Still i am learner of this tool.

**Comment by m0bilesecurity** [comment]
Hey @vikramn99, thanks for using RMS!

You can watch some DEMOs and Tutorials on my YouTube Channel: https://www.youtube.com/channel/UCsMn0JsCTAM73AdEZgwUBwg/

Best

**Comment by vikramn99** [comment]
Sir, please provide a additional option to load the custom lib files.
We need to analyse that files, RMA loads only .java files.
