### ISSUE TITLE
Custom lib classes  hooking

### ISSUE THREAD

**Issue by vikramn99** [m0bilesecurity/RMS-Runtime-Mobile-Security#38]
Shall we can get a optional feature to hook the custom lib classes ?
Because RMS loads only .java files, but we need other extension classes also(like .cpp, .jsp etc)

**Comment by m0bilesecurity** [comment]
Hey @vikramn99,
RMS already offers tons of default FRIDA scripts.
If you have some time you can improve the project and add some cool scripts!
Many thanks

**Comment by vikramn99** [comment]
Yeah, it's a amazing feature, but whenever RMS doesn't loads that custom
lib classes or files, then how we can hook that classes ?
