### ISSUE TITLE
Loading required classes at startup

### ISSUE THREAD

**Issue by kakakhan2016** [m0bilesecurity/RMS-Runtime-Mobile-Security#39]
Thanks for awesome and great RMS. During testing small crack me it load all classes but testing on real app, it does not load all  classes.

For example after static analysis of apk,  I found classes to be monitor is in com.myapp.recroder.register but it load 645 classes but rms does not load this specific class and others important one .  Filter does not work as it only filter loaded classes. I tried class differences but did not find class.  Loading default script is related to script load. I did not figure out how to restrict loading to only specific main class like .com\... instead of loading all others like android, com.crashlytics.androidm androidx, kotlin etc..

**Comment by m0bilesecurity** [comment]
Ciao @kakakhan2016,
can you kindly share the APK file?

I'm sorry but during the startup of the app it is not possible to filter out unwanted classes. 

Many thanks

**Comment by kakakhan2016** [comment]
Thanks for reply. Its sad that we can not control loading of classes. it seems that rms has limitation of loading classes,  otherwise if all classes are loaded than filtering them out for any specific will be really awesome feature. Will test it on small app or classes under 650.
