### ISSUE TITLE
RMS Can't locate device

### ISSUE THREAD

**Issue by sventek-s** [m0bilesecurity/RMS-Runtime-Mobile-Security#40]
Hi,

I am using a rooted device, so I rooted the device by patching the the boot image with magisk then flashed the patched boot image. I am using fridaloader app  and I can confirm that fridaserver is running perfectly fine. But still RMS can't connect to the device, tried using both USB and wifi adb but nothing works, kindly assist. I have restarted both devices and also frida-server multiple times and also changed system package but nothing works, below are images and screenshots.

1. Confirming frida server is working
![image](https://user-images.githubusercontent.com/70489395/96830110-8c0da180-1443-11eb-8e71-42a127a92d0e.png)

2. ADB working
![image](https://user-images.githubusercontent.com/70489395/96830244-c9722f00-1443-11eb-898a-f19c09e10d01.png)

3. Chrome
![image](https://user-images.githubusercontent.com/70489395/96830399-135b1500-1444-11eb-88ee-e495d5e4905e.png)

4. Mozilla
![image](https://user-images.githubusercontent.com/70489395/96830491-32f23d80-1444-11eb-857c-3bd40a224fdf.png)

Kindly assist, don't know what else to do.

**Comment by m0bilesecurity** [comment]
Hey @sventek-s,
thanks for using RMS.

**Everything seems correct.** 

Few things you can check:
* please make sure that only 1 device is connected to your PC (multiple devices are currently not supported)
* RMS is launched after the frida-server

Best

**Comment by sventek-s** [comment]
Ohhhh, damn thanks alot, the second option helped ... you should note that down also :smile: on the readme.

Regards.

**Comment by m0bilesecurity** [comment]
Super! 
Let me know what you think of RMS as soon as you have time to play with the tool 😉
