### ISSUE TITLE
iOS Device Error - Internal Server Error : The server encountered an internal error 

### ISSUE THREAD

**Issue by ganesh2183** [m0bilesecurity/RMS-Runtime-Mobile-Security#42]
Installed RMS and can access via http://127.0.0.1:500

iOS device is detected, but when trying to attach or spawn an app I am getting the following error page (unable to attach screenshot)

Internal Server Error : The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I am trying this on Non-jailbroken iOS device (iPhone 11 Pro Max OS:13.5.1)

Package Name: com.nav.key
Mode: Spawn
Device: Device(id="00008030-0002715E1E88802E", name="iPhone", type='usb')
BETA: False
Frida Startup Script: None
APIs Monitors: None

unable to attach to the specified process
SpringBoard is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
[2020-11-05 01:57:20,004] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "mobilesecurity.py", line 428, in device_management
    pid = device.spawn([target_package])
  File "/Users/babugan/Library/Python/3.8/lib/python/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/Users/babugan/Library/Python/3.8/lib/python/site-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: connection closed

Frida CLI is working fine,

frida -U KeyNav
     ____
    / _  |   Frida 14.0.5 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
                                                                                
[iPhone::KeyNav]->ObjC.available
true
[iPhone::KeyNav]->

May I know what I missing here, how to fix this issue ??

**Comment by m0bilesecurity** [comment]
Hey @ganesh2183,
```
unable to attach to the specified process
SpringBoard is NOT available on your device or a wrong OS has been selected. For a better RE experience, change it via the Config TAB!
frida.NotSupportedError: connection closed
```
If you are using RMS on a NON jailbroken iOS device, you are forced to use FRIDA in [**Gadget mode**](https://frida.re/docs/gadget/).

**Comment by ganesh2183** [comment]
I connected to Non Jailbroken device using Frida gadget. I am able to list process/appliation running in iOS device using **frida-ps -U**

When I try with 'Spawn' getting 500 Internal Server Error page. But it works fine with 'Attach'. Why ??

Also when i click on Static Analysis again getting 500 Internal Server Error page

Please help on this to fix.
