### ISSUE TITLE
Docker-compose error - default.js no such file or directory

### ISSUE THREAD

**Issue by sdcampbell** [m0bilesecurity/RMS-Runtime-Mobile-Security#44]
docker-compose up
Creating network "rms-runtime-mobile-security_default" with the default driver
Building rms
Step 1/16 : FROM python:3.7.7-slim
 ---> 4cbd5021babc
Step 2/16 : RUN mkdir -p /app/
 ---> Running in 1a038aecaf6e
Removing intermediate container 1a038aecaf6e
 ---> d9fab1209897
Step 3/16 : WORKDIR /app/
 ---> Running in 171c4b9d38ee
Removing intermediate container 171c4b9d38ee
 ---> cef4a4726c4b
Step 4/16 : COPY static/ ./static/
 ---> 58979a040242
Step 5/16 : COPY custom_scripts/ ./custom_scripts/
 ---> 899c2b4e7df1
Step 6/16 : COPY templates/ ./templates/
 ---> b65b84635cd4
Step 7/16 : COPY config.json default.js mobilesecurity.py requirements.txt ./
ERROR: Service 'rms' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder243707710/default.js: no such file or directory

**Comment by m0bilesecurity** [comment]
Hey @sdcampbell,
the path of the js agent has changed. You only need to update the Dockerfile with the new path.

Replace "default.js" with  "/agent/RMS_core.js"

If it works please open a PR with the fixed Dockerfile 😉
Many thanks

**Comment by sdcampbell** [comment]
That worked, thanks. Once it got past that step there were more errors. I'll open separate issues for those, and once all are worked out I'll submit a PR. Thanks

**Comment by m0bilesecurity** [comment]
Hey @sdcampbell,
was it necessary to change anything else?

**Comment by sdcampbell** [comment]
I need to test further. So far it passed that one build step and built the container image but IDK if the app works. I'll test it NLT tonight after work and get back to you.

**Comment by m0bilesecurity** [comment]
Hey @sdcampbell,
the path of the RMS agent has been fixed in commit 27d528fc84e97ba0218fa950fac4510624fc84c8 😉

**Comment by sdcampbell** [comment]
Thank you
