### ISSUE TITLE
Issues with classes and output data

### ISSUE THREAD

**Issue by vikramn99** [m0bilesecurity/RMS-Runtime-Mobile-Security#45]
1)When i'll try to capture the some classes 
If output is string, then no problem.
If output is array then output like this [object, object].

2) Many of (like com.somepackage.class) classes are not loading for some apps. That time it's difficulty to capture or trace the data.

**Comment by m0bilesecurity** [comment]
Hey @vikramn99,
Please provide the APK and some examples otherwise I cannot help.
Thanks
