### ISSUE TITLE
device_manager.getRemoteDevice is not a function

### ISSUE THREAD

**Issue by b1gb1t** [m0bilesecurity/RMS-Runtime-Mobile-Security#47]
https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/blob/78621860d558bcdca5abb038de52cd3da949ae6b/app.js#L375

The correct function is 
`device_manager.addRemoteDevice`

Also, the correct function argument is 
`config.device_args.host`

So the whole line should be
`device = await device_manager.addRemoteDevice(config.device_args.host)`

Regards

**Comment by m0bilesecurity** [comment]
Hey @b1gb1t many thanks for the fix!
PR has been merged 🙏🏻 🙏🏻 🙏🏻
