### ISSUE TITLE
RMS Install - Error related to Frida

### ISSUE THREAD

**Issue by zpatshueh** [m0bilesecurity/RMS-Runtime-Mobile-Security#53]
**Describe the bug** [Required]
RMS-Runtime-Mobile-Security % npm install -g rms-runtime-mobile-security
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/RMS-Runtime-Mobile-Security -> /usr/local/lib/node_modules/rms-runtime-mobile-security/rms.js
/usr/local/bin/rms -> /usr/local/lib/node_modules/rms-runtime-mobile-security/rms.js

> frida@14.2.2 install /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=15.3.0 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/15.3.0/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida
gyp ERR! node -v v15.3.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@14.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@14.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

See Log -attached

**To Reproduce** [Required]
npm install -g rms-runtime-mobile-security

**Expected behavior** [Optional]
Installation should work

**Desktop (please complete the following information):** [Required]
 - OS: MAC OS - 10.15.7 (19H2)
 - Browser NA

**Smartphone (please complete the following information):** [Required]
NA

**Console Logs** [Required]
NA

**Comment by m0bilesecurity** [comment]
Hey @zpatshueh 
please read some possible solution here #50 and here #51 
Thanks
