### ISSUE TITLE
[iOS 12 only] RMS Crashing when spawning an app - iOS

### ISSUE THREAD

**Issue by abhilashnigam** [m0bilesecurity/RMS-Runtime-Mobile-Security#55]
When I try to follow your exact steps in spawning the application the iOS Device re-springs. I have added the video explaining the issue. Also if I am able to spawn the application and I click the Load classes button the RMS crashes. Could You please help. I have tried the same on a Mac but it still gives me the same issue. The error on the RMS terminal is shown in the screenshot attached. Objection seems to be working fine. 

I am using - iPhone 5s -12.4.8

![RMS Error Screenshot](https://user-images.githubusercontent.com/39301359/104415283-c183e000-5597-11eb-95db-c317903f15d5.png)
![RMS Error Video](https://user-images.githubusercontent.com/39301359/104414808-dc098980-5596-11eb-83ed-ed77288682b5.mp4)

**Comment by m0bilesecurity** [comment]
Hey @abhilashnigam,
many thanks for all the info provided.
Unfortunately it seems an issue that only occurs on iOS 12. 

I'm not able to reproduce it on iOS 13 and, unfortunately, I don't have an iOS 12 device.

Sorry
Paolo
