### ISSUE TITLE
Http or Https data capture

### ISSUE THREAD

**Issue by vikramn99** [m0bilesecurity/RMS-Runtime-Mobile-Security#56]
If we get frida script or API to capture http or https data of android apps, it would be great for us :).
RMS sometimes fail to load some classes. If we try to do capture with script template, it gives error.
Related to objection, some implementations are needed, like manual class or method hook support.

RMS is a great tool with GUI, only some limitations and issues are there, if that all solved, then this would be the best for android pentest.

**Comment by m0bilesecurity** [comment]
Hey @vikramn99, 
Please provide some examples.
Best
Paolo

**Comment by vikramn99** [comment]
Please look out this one.
https://github.com/Ch0pin/medusa
