### ISSUE TITLE
HashMap Hook

### ISSUE THREAD

**Issue by vikramn99** [m0bilesecurity/RMS-Runtime-Mobile-Security#57]
If we get hashmap hook template or script, it would be great :)

Please also look out this one.
This one supports http or https data capturing and other some things also
https://github.com/Ch0pin/medusa

**Comment by m0bilesecurity** [comment]
Thanks @vikramn99.

It would be great if you could work on some new stuff.
I close the issue for now. 
As soon as you have something ready, please open a PR.
Best
