### ISSUE TITLE
Unable to connect to device

### ISSUE THREAD

**Issue by DeserranoJorden** [m0bilesecurity/RMS-Runtime-Mobile-Security#58]
I know the issue has been brought on a couple of times before here.
But I have no clue on how to proceed here.

My setup:
Galaxy Tab A (Android version 9)
MacOS Big Sur 11.1

Frida-Tools version 12.11.18
Frida-server version 12.11.11
([https://deserrano.com/frida-version.png](https://deserrano.com/frida-version.png))

The device is currently connected to my mac through USB.

As shown in this screenshot, I can use frida normally and the server is running on the device.
But I am still however unable to connect with rms.
[https://deserrano.com/frida-connected.png](https://deserrano.com/frida-connected.png)

The tool looks awesome and I would love to try it out.

Kr

**Comment by m0bilesecurity** [comment]
Hey @DeserranoJorden 
you need to update your frida-server. 12.11.11 is very OLD 😉

RMS requires "frida": "^14.2.1". 

Official Guide: https://frida.re/docs/android/ or you can use **MagiskFrida** or **FridaLoader**

Best

**Comment by DeserranoJorden** [comment]
Hey @m0bilesecurity 

Thanks for these remarks. This worked for me.
I still have the older version running as my IOS tablet cannot update to a higher version.
But it works on Android for now.

Kind Regards
