### ISSUE TITLE
RMS doesn't work

### ISSUE THREAD

**Issue by Mac85** [m0bilesecurity/RMS-Runtime-Mobile-Security#60]
When I ran ./rms.js I obtained _"Error: Cannot find module 'frida'"_
If I try to install frida with "npm install frida" I obtained this error: _"npm ERR! gyp: binding.gyp not found "_
In my opinion the problem is the version of python called. it could be? Since I have several versions of python installed how do I get RMS to point to the correct version?
Thank you !!

**Comment by m0bilesecurity** [comment]
Hey @Mac85 
please read some possible solution here #50 and here #51
Thanks
