### ISSUE TITLE
thanks to contubuters to support Stetho script,

### ISSUE THREAD

**Issue by delokman** [m0bilesecurity/RMS-Runtime-Mobile-Security#64]
thanks to contubuters to support Stetho script,

but as u know, facebook team worked on flipper ,
https://github.com/facebook/flipper

i need Frida script to load flipper,

**Comment by m0bilesecurity** [comment]
Hey @delokman,
Do you have time to work on this?
It will be great!
Thanks

**Comment by delokman** [comment]
> Hey @delokman,
> Do you have time to work on this?
> It will be great!
> Thanks

Hey
yes,
but im noob on frida and i fail ,
can u help?
