### ISSUE TITLE
Can't Load all Classes

### ISSUE THREAD

**Issue by oynomed** [m0bilesecurity/RMS-Runtime-Mobile-Security#66]
RMS can't load all the classes on an android, is there a limitation of classes loaded, see screenshots of JADX class and RMS loaded class.
https://i.imgur.com/AjBEqPh.png

or maybe I miss something.

**Comment by m0bilesecurity** [comment]
Are you sure that the class has been loaded in memory?
RMS performs a dump of the classes that have been loaded in memory. If the name of the class contains the word  "oauth", the suggestion is to try to perform the dump during the login pause 😉
