### ISSUE TITLE
MEmu Android Emulator support

### ISSUE THREAD

**Issue by Kaspek2480** [m0bilesecurity/RMS-Runtime-Mobile-Security#68]
**Describe the bug** [Required]
Frida is running on device, frida-ps -U work and i am getting all already running apps but when i use RMS to connect with device i got an error

**Desktop (please complete the following information):** [Required]
 - OS: Windows 10 x64
 - Browser Brave

**Smartphone (please complete the following information):** [Required]
 - Device: MEmu
 - OS: Android 7.1
 - Frida Server version: latest

**Console Logs** [Required]
If applicable, add console logs.

![image](https://user-images.githubusercontent.com/33702004/113941121-da024000-97fe-11eb-89ff-50e0713fb170.png)
![image](https://user-images.githubusercontent.com/33702004/113941156-e6869880-97fe-11eb-9dfc-36911814ce5a.png)

**Comment by m0bilesecurity** [comment]
Hey @Kaspek2480,
unfortunately MEmu is currently not supported by RMS. 
More than welcome if you have some time to understand and fix the issue.
Otherwise I strongly suggest to use AVD or Genymotion 😉
