### ISSUE TITLE
RMS not recognizing device

### ISSUE THREAD

**Issue by jumbofreak** [m0bilesecurity/RMS-Runtime-Mobile-Security#69]
Trying RMS on chrome browser but it isn't able to recognize device. 
Frida-ls-devices picks up device, frida server started before RMS. RMS restarted few times. Tried both Chrome/Firefox but still no luck with device recognition. Any idea what's going on here. Is there a way to check if Chrome has access to usb interface ? or any logs to check ?

>>frida-ps -U
  PID  Name
-----  ---------------------------------------------------
  624  ATFWD-daemon
13048  adbd
  667  android.hardware.biometrics.fingerprint@2.1-service
  540  android.hardware.cas@1.0-service
  541  android.hardware.configstore@1.0-service
  542  android.hardware.dumpstate@1.0-service.bullhead
  543  android.hardware.graphics.allocator@2.0-service
 10586  frida-server

>>frida-ls-devices
Id                Type    Name
----------------  ------  ------------
local             local   Local System
1c3dd21aaa7ef6  usb     Nexus 5X
socket            remote  Local Socket

**Comment by m0bilesecurity** [comment]
Hey @jumbofreak,
Can you show me the RMS error (output of the terminal).
Many thanks

**Comment by jumbofreak** [comment]
Thanks for the reply. What I noticed was, when I start frida-server process on device, RMS fails to detect . If I kill the frida-server process on the device then it is able to recognize device. I'm using frida 14.2.13

This is what I get on console
_________________________________________________________
RMS - Runtime Mobile Security
Version: 1.5.7
by @mobilesecurity_
Twitter Profile: https://twitter.com/mobilesecurity_
_________________________________________________________

Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[Error: Unable to handle 64-bit processes due to build configuration]

**Comment by m0bilesecurity** [comment]
mmm great 😉
Anyway the error sounds very strange. It seems that you pushed a wrong version of the frida-server (you need the arm version instead of the arm64).

Best
Paolo

**Comment by jumbofreak** [comment]
sorry for the late reply, my device IS 64 bit , frida on its own fine outside of RMS, I think it's just RMS pulling it wrong ?
this is the output of uname -a, 
bullhead:/ $ uname -a
Linux localhost 3.10.73-g9a1b43ed0b83 #1 SMP PREEMPT Fri Jan 12 23:03:56 UTC 2018 **aarch64**
