### ISSUE TITLE
Ideas and bugs

### ISSUE THREAD

**Issue by 4val0v** [m0bilesecurity/RMS-Runtime-Mobile-Security#7]
1) Run a FRIDA script at startup - please using Ajax, or in the request pass the package name
   - _After selecting a custom script, you must re-specify the package name_
2) Console Output - using Ajax (`.append()`), currently page is always reload
   - _The output always moves to the top, which is inconvenient (_
   - _Also not possible to normally copies output with turn on "Auto Refresh Page"._
3) Console Output - There is no way to clear output (
   - _Need restart the python process :(_

**Comment by m0bilesecurity** [comment]
Hey @4val0v many thanks for your feedback.
Yes the UI needs to be improved a lot 😉. It is totally static at the moment.
I've decided to create an open source project hoping for a support from the Github community.

AFAIK @realgam3 is already working to add API support and WebSocket connection for the Console Output.

**Comment by 4val0v** [comment]
Also would like to be have possibility to set class names in the Hook filter **for ignore**, eg.: `com.google.android.gms., android.support., android.graphics., android.content.res.` etc...

> AFAIK @realgam3 is already working to add API support and WebSocket connection for the Console Output.

Great, this is good news )

> I've decided to create an open source project hoping for a support from the Github community.

Unfortunately, I don't have free time now, but later I will be happy to help

**Comment by fmdmpoli** [comment]
After configuring genymotion host the app stops responding. Even in debug mode there's no output in console. Any idea what could be happening?

**Comment by m0bilesecurity** [comment]
Ciao @fmdmpoli can you kindly provide more info about the issue?

**Comment by fmdmpoli** [comment]
> After configuring genymotion host the app stops responding. Even in debug mode there's no output in console. Any idea what could be happening?

I went to **Config** > Selected **Remote** > Inserted my **local address IP (ex. 192.168.0.10:24800)** and the RMS stopped responding after the POST request, it still loading and with no answer and no output on server console.

Arch:
RMS OS: Kali Linux fresh install (in a local server)
Browser: Chrome (on my Macbook)
Smartphone: Genymotion Android 8 / API 26 (on my Macbook)
Frida Server version: Frida 12.8.20

**Comment by m0bilesecurity** [comment]
RMS is not able to find the remote device. Is FRIDA cli working?

**Comment by fmdmpoli** [comment]
> RMS is not able to find the remote device. Is FRIDA cli working?

Ya. It's perfectly running frida-server and frida-cli.

**Comment by m0bilesecurity** [comment]
@fmdmpoli try to have a look at **get_device()** in **mobilesecurity.py**
Let me know if you find the issue

**Comment by fmdmpoli** [comment]
> @fmdmpoli try to have a look at **get_device()** in **mobilesecurity.py**
> Let me know if you find the issue

It worked by running everything on the same computer. Sadly I couldn't make it work by running through my local network. 
Later I'll try figuring out why RMS gets lost when Genymotion is in a in a different computer.

Tks a lot!

**Comment by m0bilesecurity** [comment]
Checkout new 1.0.3 release 😉
