### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by soh0ro0t** [m0bilesecurity/RMS-Runtime-Mobile-Security#70]
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/build/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/build/Debug/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/build/Release/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/out/Debug/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/Debug/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/out/Release/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/Release/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/build/default/frida_binding.node
 → /usr/local/lib/node_modules/rms-runtime-mobile-security/node_modules/frida/compiled/10.19.0/linux/x64/frida_binding.node

**Comment by m0bilesecurity** [comment]
Hey @ju5tme 
please read some possible solutions here #50 and here #51
Thanks
