### ISSUE TITLE
SpringBoard is NOT available on your device!

### ISSUE THREAD

**Issue by oynomed** [m0bilesecurity/RMS-Runtime-Mobile-Security#72]
As what title says, I'm using Jailbreak IPAD AIR IOS v12.5.1, see screenshot
https://i.imgur.com/ElXLtgh.png

What is the exact System Package to put in Config?

**Comment by m0bilesecurity** [comment]
Ciao @oynomed,
default one for iOS is "SpringBoard" and, as you can imagine, it should be available also on iOS 12.
Can you share RMS terminal logs?
What's the error if you try to attach the SpringBoard process directly via Frida?
Thanks

**Comment by oynomed** [comment]
Sorry for late reply, here is the screenshots
https://i.imgur.com/oNYmUUy.png
https://i.imgur.com/HQU05lK.png

**Comment by oynomed** [comment]
any updates bro...

**Comment by m0bilesecurity** [comment]
Sorry but I don't have an iOS 12 device and I can't replicate the issue.
