### ISSUE TITLE
Filter in Console Output for hooked methods

### ISSUE THREAD

**Issue by 0x0msg** [m0bilesecurity/RMS-Runtime-Mobile-Security#75]
**Is your feature request related to a problem? Please describe.**
Multiple methods hooked at once makes it  difficult to find the data passed from app and hard to know which method is triggered for the data entered

**Describe the solution you'd like**
Search filter for each console output screen

**Comment by m0bilesecurity** [comment]
Hey @0x0msg 
I'm sorry but your request is not so clear. Can you kindly provide more details?
Many thanks
