### ISSUE TITLE
RMS Hangs with Frida 15

### ISSUE THREAD

**Issue by MrTuxracer** [m0bilesecurity/RMS-Runtime-Mobile-Security#78]
**Describe the bug** [Required]
When using RMS with Frida > 15, it hangs forever. It affects both Android and iOS and is independent of what kind of connection is used (USB, Remote, Serial). The development version is also affected. The Quick smoke-test is working fine and shows expected results.

**To Reproduce** [Required]
1. Install latest RMS and latest frida-tools
2. Connect your iOS/Android via USB
3. Start rms 
4. Try to connect to the web interface of RMS, which will time-out
5. Disconnect the iOS/Android device and RMS will load properly

**Desktop (please complete the following information):** [Required]
 - MacOS 11.5
 - Browser: Latest Google Chrome

**Smartphone (please complete the following information):** [Required]
 - Device: IPad 6th Generation, Google Pixel, Android Emulator
 - OS: doesn't matter
 - Frida Server version: 15.0.12

**Console Logs** [Required]
When using USB connection:
No log at all, it just hangs

When using remote connections:
``
[Error: Unexpected lack of content trying to read a line]
[Error: Unable to connect to remote frida-server]
``

When using serial connection:
``
TypeError: device_manager.getDevice is not a function
    at /usr/local/lib/node_modules/rms-runtime-mobile-security/rms.js:383:38
``

**Comment by MrTuxracer** [comment]
It works fine again, when I downgrade frida-server to i.e. 14.2.1

**Comment by m0bilesecurity** [comment]
Hey @MrTuxracer,
do you know what's the issue? If yes and you have time to fix please open a PR 😉
Many thanks

**Comment by m0bilesecurity** [comment]
Just tried to update FRIDA to v15 and everything is working fine.
Are you sure the issue is related to FRIDA v15?
Thanks

**Comment by MrTuxracer** [comment]
I've just updated to RMS 1.5.8 which seems to fix the issue. Maybe it's just been the npm dependency?! 
Thanks anyways!
