### ISSUE TITLE
Activity hook template

### ISSUE THREAD

**Issue by d68m** [m0bilesecurity/RMS-Runtime-Mobile-Security#80]
In generally we can hook all other methods and data input and output of methods or classes, but not same in the case of activity.

In this activity supply, we don't know or we not getting the actual data what is taking as or given as input .

We just see like as a input

`com.example.class.activity@83f4afs`

Here we not able to see what actual data is supplied to that class or method.

Is any way, so we can hook activity input data ?

**Comment by m0bilesecurity** [comment]
Hey @d68m,
sorry issue is not clear. Please provide more info if possibile
