### ISSUE TITLE
Frida attach not working

### ISSUE THREAD

**Issue by venkata16sidhartha** [m0bilesecurity/RMS-Runtime-Mobile-Security#84]
While keeping the "spawn or attach" to attach no app is opening, even when app is open in the device or not open. 
This is even for com.android.calculator2 and no frida script to load in startup!!!

Please look into it !!!

**Comment by m0bilesecurity** [comment]
Hey @venkata16sidhartha,
Make sure to use the latest frida client on your device.
I've also updated the RMS npm package (v1.5.11) with the latest frida version (15.1).
Please try it. 
Just tested and I can confirm that everything is working fine.

Paolo
