### ISSUE TITLE
Connecting via NoxPLayer 7.0.2.0

### ISSUE THREAD

**Issue by nullcult** [m0bilesecurity/RMS-Runtime-Mobile-Security#87]
Am having problems connecting RMS to NoxPLayer.
Am using the remote option setting 127.0.0.1:62001 as the device but it's not connecting.
Any hints?

Thanks

**Comment by m0bilesecurity** [comment]
Hi @nullcult,
sorry but I'm not planning to support NoxPlayer at the moment but feel free to extend the support if you have some free time.

Thanks
