### ISSUE TITLE
remember package config

### ISSUE THREAD

**Issue by Nriver** [m0bilesecurity/RMS-Runtime-Mobile-Security#94]
I am a noob in frida scripts, and often make app carsh. Every time after crash, I have to manually select os, package name, reinput the sciripts, etc...
It would be nice to make rms remember what app that I inputed last time to avoid repeated work.

**Comment by m0bilesecurity** [comment]
Maybe in a future version, zero free time at the moment 😭.
Thanks for the suggestion.
