### ISSUE TITLE
RMS on Fire TV 

### ISSUE THREAD

**Issue by Aniketh01** [m0bilesecurity/RMS-Runtime-Mobile-Security#95]
Hi,

The readme file says that RMS has support for Fire TV, however, I tried it with Fire TV lite and it does not seem to work. The Frida agent gets stuck indefinitely and there is no way to connect to the TV using RMS. Is this a known issue that can be resolved someway?

**Comment by m0bilesecurity** [comment]
Ciao @Aniketh01,
yes I tested RMS on a rooted Fire TV 4K. 
Please note that the default package hooked by RMS ("com.android.systemui") is not working with the Fire TV. 
You can change it the via the config tab. I don't remember at the moment the package used for my tests but it was something related to the settings panel.
